### ISSUE TITLE
awssociate require option parameter to choose if XRay service wrap is desired or not

### ISSUE THREAD

**Issue by BijiteshK** [MechanicalRock/sigma#5]
There is a scenario where we don't want aws-xray-sdk wrap around AWS services in "awssociate". Like, we want to run integration test where lambda is NOT being executed. As we have 'aws-xray-sdk' in the "node_module" folder, the awssociate would return the service wrapped with XRAY, but the code will be failing saying "Failed to get the current sub/segment from the context". This is happening in one module where we have XRay instrumentation done in lambda codes but the integration test is failing with such error.

**Comment by temyers** [comment]
For this scenario, when using Jest, you can create a mock library for XRay, and configure it within your module.

See: https://jestjs.io/docs/en/manual-mocks

**Comment by temyers** [comment]
We have built a mock implementation available here:
See: https://github.com/MechanicalRock/aws-xray-mock
